export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const hoge = 'hoge'

  return (
    <html lang="en">
      <h1>{hoge}</h1>
      <body>{children}</body>
    </html>
  )
}
